export default images = {
    simpleLogo: require('../Images/logo.png'),
    logo: require('../Images/logo-full.svg'),
    logoIcon: require('../Images/logo-icon.png'),
    logoIcon2: require('../Images/logo-icon2.png'),
    texture01: require('../Images/textures/texture01.png'),
    texture01Blue: require('../Images/textures/texture01-blue.png'),
    texture02: require('../Images/textures/texture02.png'),
    texture02Blue: require('../Images/textures/texture02-blue.png'),
    texture03: require('../Images/textures/texture03.png'),
    texture03Blue: require('../Images/textures/texture03-blue.png'),
    texture04: require('../Images/textures/texture04.png'),
    texture04Blue: require('../Images/textures/texture04-blue.png'),
    texture05: require('../Images/textures/texture05.png'),
    texture05Blue: require('../Images/textures/texture05-blue.png'),
    texture06Blue: require('../Images/textures/texture06-blue.png'),
    texture07: require('../Images/textures/texture07.png'),
    texture08: require('../Images/textures/texture08.png'),
    texture09: require('../Images/textures/texture09.png'),
    textureGray01: require('../Images/textures/texture-gray01.png'),
    textureGray02: require('../Images/textures/texture-gray02.png'),
    textureGray03: require('../Images/textures/texture-gray03.png'),
    textureDrawer: require('../Images/textures/texture-drawer.png'),
    textureBlue01: require('../Images/textures/texture-blue01.png'),

    movingWatermark : require('../Images/watermark-box.png'),
    housingWatermark : require('../Images/watermark-house.png'),
    costOfLivingWatermark: require('../Images/watermark-cost-of-living.png'),
    weatherWatermark: require('../Images/watermark-weather.png'),
    demographicWatermark: require('../Images/watermark-demographic.png'),
    safetyWatermark: require('../Images/watermark-safety.png'),
    commuteWatermark: require('../Images/watermark-commute.png'),

    introIllustration1: require('../Images/Intro/welcome.png'),
    introIllustration2: require('../Images/Intro/planning.png'),
    introIllustration3: require('../Images/Intro/lump-sum.png'),
    introIllustration4: require('../Images/Intro/concierge.png'),

    iconArrowheadBlue: require('../Images/icons/arrowhead-right-blue.png'),
    iconArrowheadSmallRightBlue: require('../Images/icons/arrowhead-righ-small-blue.png'),
    iconArrowheadRightWhite : require('../Images/icons/arrowhead-right-white.png'),
    iconArrowheadLeftBlack : require('../Images/icons/arrowhead-left-black.png'),
    iconArrowheadLeftWhite : require('../Images/icons/arrowhead-left-white.png'),
    iconArrowheadSmallRightWhite : require('../Images/icons/arrowhead-small-right-white.png'),
    iconPulldownWhite : require('../Images/icons/icon-pulldown-arrow.png'),
    iconRadioOff: require('../Images/icons/radio-off.png'),
    iconRadioOn: require('../Images/icons/radio-on.png'),
    iconDrawerMenu : require('../Images/icons/menu.png'),
    iconAdult : require('../Images/icons/adult-white.png'),
    iconAdultGray : require('../Images/icons/adult-gray.png'),
    iconChild : require('../Images/icons/child-white.png'),
    iconChildGray : require('../Images/icons/child-gray.png'),
    iconBed : require('../Images/icons/bed-white.png'),
    iconShower : require('../Images/icons/shower.png'),
    iconBullet: require('../Images/icons/bullet.png'),
    iconCalendarBlue : require('../Images/icons/calendar-blue.png'),
    iconCalendarSmallWhite : require('../Images/icons/calendar-small-white.png'),
    iconCalendarSmallBlue : require('../Images/icons/calendar-small-blue.png'),
    iconCheckmark: require('../Images/icons/checkmark-green.png'),
    iconXGray: require('../Images/icons/x-gray.png'),
    iconXWhite: require('../Images/icons/x-white.png'),
    iconXOrange : require('../Images/icons/x-orange.png'),
    iconXOrange2 : require('../Images/icons/x-orange-2.png'),
    iconExternalLink: require('../Images/icons/arrow-upright-blue.png'),
    iconShow: require('../Images/icons/show.png'),
    iconHide: require('../Images/icons/hide.png'),
    iconHomeBlue : require('../Images/icons/home-blue.png'),
    iconWorkBlue : require('../Images/icons/work-blue.png'),
    iconPhone: require('../Images/icons/phone.png'),
    iconI: require('../Images/icons/i.png'),
    iconLocationBlack : require('../Images/icons/location-black.png'),
    iconLocationSmallWhite : require('../Images/icons/location-small-white.png'),
    iconLocationBlue : require('../Images/icons/location-blue.png'),
    iconRightArrow : require('../Images/icons/arrow-right-blue.png'),
    iconBell: require('../Images/icons/bell.png'),
    iconBell2: require('../Images/icons/bell2.png'),
    iconBellGray: require('../Images/icons/bell-gray.png'),
    iconInventory: require('../Images/icons/inventory.png'),
    iconDolly: require('../Images/icons/dolly.png'),
    iconMaterials: require('../Images/icons/materials.png'),
    iconTruckGray: require('../Images/icons/truck-gray.png'),
    iconBoxes : require('../Images/icons/boxes.png'),
    iconAdd : require('../Images/icons/add.png'),
    iconEdit: require('../Images/icons/edit.png'),
    iconEditBlue: require('../Images/icons/edit-blue.png'),
    iconEditLightGray: require('../Images/icons/edit-light-gray.png'),
    iconChatSmall: require('../Images/icons/chat-small.png'),
    iconEmail: require('../Images/icons/email.png'),
    iconProtipIllustration: require('../Images/icons/protip-illustration.png'),
    iconTime: require('../Images/icons/time.png'),
    iconTimeBlue: require('../Images/icons/time-blue.png'),
    iconLaborBlue: require('../Images/icons/labor-blue.png'),
    iconCommuteTime: require('../Images/icons/commute-time.png'),
    iconCostOfLiving: require('../Images/icons/cost-of-living.png'),
    iconEducation: require('../Images/icons/education.png'),
    iconPopulation: require('../Images/icons/population.png'),
    iconSafety: require('../Images/icons/safety.png'),
    iconWeather: require('../Images/icons/weather.png'),
    iconBuilding: require('../Images/icons/building.png'),
    iconHouse: require('../Images/icons/house.png'),
    iconRealtor: require('../Images/icons/realtor.png'),
    iconCommute: require('../Images/icons/commute.png'),
    iconClock: require('../Images/icons/clock.png'),
    iconOfferInline: require('../Images/icons/offer-inline.png'),
    iconInstagram: require('../Images/icons/instagram.png'),
    iconFacebook: require('../Images/icons/facebook.png'),
    iconTwitter: require('../Images/icons/twitter.png'),
    iconLinkedIn: require('../Images/icons/linkedin.png'),
    weather01d: require('../Images/weather/01d.png'),
    weather01n: require('../Images/weather/01n.png'),
    weather02d: require('../Images/weather/02d.png'),
    weather02n: require('../Images/weather/02n.png'),
    weather03d: require('../Images/weather/03d.png'),
    weather03n: require('../Images/weather/03n.png'),
    weather04d: require('../Images/weather/04d.png'),
    weather04n: require('../Images/weather/04n.png'),
    weather09d: require('../Images/weather/09d.png'),
    weather09n: require('../Images/weather/09n.png'),
    weather10d: require('../Images/weather/10d.png'),
    weather10n: require('../Images/weather/10n.png'),
    weather11d: require('../Images/weather/11d.png'),
    weather11n: require('../Images/weather/11n.png'),
    weather13d: require('../Images/weather/13d.png'),
    weather13n: require('../Images/weather/13n.png'),
    weather50d: require('../Images/weather/50d.png'),
    weather50n: require('../Images/weather/50n.png'),

    applePay : require('../Images/Packing/apple-pay.png'),
    boxIcon: require('../Images/Packing/MaterialsIcons/Box.png'),
    bubbleWrapIcon: require('../Images/Packing/MaterialsIcons/Bubble_Wrap.png'),
    packingPaperIcon: require('../Images/Packing/MaterialsIcons/Packing_Paper.png'),
    stretchWrapIcon: require('../Images/Packing/MaterialsIcons/Stretch_Wrap.png'),

    loader: require('../Images/loading.gif'),

    happyWhiteEmoji : require('../Images/Feedback/happy-white.png'),
    neutralWhiteEmoji : require('../Images/Feedback/neutral-white.png'),
    unhappyWhiteEmoji : require('../Images/Feedback/unhappy-white.png'),

    happyYellowEmoji: require('../Images/Feedback/happy-yellow.png'),
    neutralYellowEmoji: require('../Images/Feedback/neutral-yellow.png'),
    unhappyYellowEmoji: require('../Images/Feedback/unhappy-yellow.png'),

    mqLocationMarker : require('../Images/toReplace/mq-location-marker.png'),
    mqLocationArrow : require('../Images/toReplace/mq-location-arrow.png'),
    mqBrandLogo : require('../Images/toReplace/mq-brand-logo.png'),
    fsDetailArrow : require('../Images/toReplace/fs-detail-arrow.png'),
    fsLocationMarker : require('../Images/toReplace/fs-location-marker-large.png'),
    fsInterrupterCalculator : require('../Images/toReplace/fs-interrupter-calculator.png'),
    fsInterrupterPiggy : require('../Images/toReplace/fs-interrupter-piggy.png'),
    fsInterrupterHandling : require('../Images/toReplace/fs-interrupter-handling.png'),
    listCardArrow : require('../Images/toReplace/list-card-arrow.png'),

    gsLogo: require('../Images/Schools/gs_logo.png'),

    lumpSumCheck: require('../Images/LumpSum/check.png'),

    cityDay: require('../Images/city-day.png'),
    cityNight: require('../Images/city-night.png'),
    oakwoodLogo: require('../Images/oakwood-logo.png'),
    checkboxChecked: require('../Images/checkbox-checked.png'),
    checkboxUnchecked: require('../Images/checkbox-unchecked.png'),
    cactus: require('../Images/cactus.png'),
    cactusGrey: require('../Images/cactus2.png'),
    tempHousingError: require('../Images/temp-housing-error.png'),
    noConnectionError: require('../Images/Errors/no-connection.png'),
    serverError: require('../Images/Errors/server-error.png'),
}
